#!/bin/sh

test -f dell2155driver_a05.dmg || curl -o dell2155driver_a05.dmg "https://github.com/elpollodiablo/dell2155_osx/raw/refs/heads/main/dell2155driver_a05.dmg"

hdiutil attach dell2155driver_a05.dmg

pkgutil --expand-full /Volumes/Printer_2155cdn\ Installer\ \&\ Application\ Dell\ A05\ Mac/Packages/Dell\ 2155cdn\ Print\ Installer.pkg ./dell2155driver_a05

hdiutil detach /Volumes/Printer_2155cdn\ Installer\ \&\ Application\ Dell\ A05\ Mac/

sudo cp -a dell2155driver_a05/installationfiles.pkg/Payload/Library/Printers/* /Library/Printers

sudo ./dell2155driver_a05/installationfiles.pkg/Scripts/postinstall
